# example docker-compose, just for testing
# ---------------------
version: '2.1'
services:
  prometheus:
    image: "prom/prometheus:v2.12.0"
    ports:
      - "9090:9090"
    volumes:
      - "./metrics.configs.sample/prometheus/prometheus.sample.yml://etc/prometheus/prometheus.yml"
  grafana:
    image: "grafana/grafana:6.3.3"
    ports:
      - "3000:3000"
    volumes:
      - "./metrics.configs.sample/grafana/provisioning:/etc/grafana/provisioning"
      - "./metrics.configs.sample/grafana/dashboards/main.json:/etc/grafana/dashboards/main.json"